// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RPG.Tests.Characters
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExperienceTableFeature : object, global::Xunit.IClassFixture<ExperienceTableFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Characters", "ExperienceTable", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ExperienceTable.feature"
#line hidden
        
        public ExperienceTableFeature(ExperienceTableFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Characters/ExperienceTable.feature", 21);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="I can get the level for a given experience points")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ExperienceTable")]
        [global::Xunit.TraitAttribute("Description", "I can get the level for a given experience points")]
        [global::Xunit.TraitAttribute("Category", "experience-table")]
        [global::Xunit.InlineDataAttribute("0", "1", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("50", "1", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("100", "2", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "2", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("300", "3", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("450", "3", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("600", "4", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("800", "4", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "5", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("1500", "5", "9", new string[0])]
        public async global::System.Threading.Tasks.Task ICanGetTheLevelForAGivenExperiencePoints(string experiencePoints, string level, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "experience-table"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("experiencePoints", experiencePoints);
            argumentsOfScenario.Add("level", level);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("I can get the level for a given experience points", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Level",
                            "ExperiencePoints"});
                table1.AddRow(new string[] {
                            "1",
                            "0"});
                table1.AddRow(new string[] {
                            "2",
                            "100"});
                table1.AddRow(new string[] {
                            "3",
                            "300"});
                table1.AddRow(new string[] {
                            "4",
                            "600"});
                table1.AddRow(new string[] {
                            "5",
                            "1000"});
#line 7
 await testRunner.GivenAsync("A experience table with the following levels:", ((string)(null)), table1, "Given ");
#line hidden
#line 14
 await testRunner.WhenAsync(string.Format("I ask for the level corresponding to {0} experience points", experiencePoints), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.ThenAsync(string.Format("I should get level {0}", level), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="I can get the experience points required for next level")]
        [global::Xunit.TraitAttribute("FeatureTitle", "ExperienceTable")]
        [global::Xunit.TraitAttribute("Description", "I can get the experience points required for next level")]
        [global::Xunit.TraitAttribute("Category", "experience-table")]
        [global::Xunit.InlineDataAttribute("0", "100", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("50", "50", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("100", "200", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("250", "50", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("300", "300", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("450", "150", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("600", "400", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("800", "200", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("1000", "0", "18", new string[0])]
        public async global::System.Threading.Tasks.Task ICanGetTheExperiencePointsRequiredForNextLevel(string experiencePoints, string experiencePointsForNextLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "experience-table"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("experiencePoints", experiencePoints);
            argumentsOfScenario.Add("experiencePointsForNextLevel", experiencePointsForNextLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("I can get the experience points required for next level", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Level",
                            "ExperiencePoints"});
                table2.AddRow(new string[] {
                            "1",
                            "0"});
                table2.AddRow(new string[] {
                            "2",
                            "100"});
                table2.AddRow(new string[] {
                            "3",
                            "300"});
                table2.AddRow(new string[] {
                            "4",
                            "600"});
                table2.AddRow(new string[] {
                            "5",
                            "1000"});
#line 31
 await testRunner.GivenAsync("A experience table with the following levels:", ((string)(null)), table2, "Given ");
#line hidden
#line 38
 await testRunner.WhenAsync(string.Format("I ask for the experience points required for next level from experience points {0" +
                            "}", experiencePoints), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync(string.Format("I should get {0} experience points", experiencePointsForNextLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ExperienceTableFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ExperienceTableFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
