version: '3'
services:
    localstack:
        image: localstack/localstack:latest
        ports:
            - "127.0.0.1:4566:4566"
        environment:
            - SERVICES=s3:4566
            - HOSTNAME=localhost
            - HOSTNAME_EXTERNAL=localhost
            - DEFAULT_REGION=us-east-2
    postgresql:
        image: "postgres:latest"
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=postgres